# ~/.config/ghostty/config

font-family = JetBrainsMono Nerd Font
font-size = 13
background-opacity = 0.95
theme = Kanagawa Wave
#
copy-on-select = false

# auto attach to tmux on open
command = /bin/bash -c 'tmux attach 2>/dev/null || tmux'

# no confirmation closing
confirm-close-surface = false

# cursor
cursor-style = block
cursor-style-blink = false
