
#prefixKey
unbind C-b
set -g prefix C-a
bind C-a send-prefix

#ESC registers immediatly 
set -sg escape-time 0

#mouse can be used
set -g mouse on 

#colors and escaping keys with ;
set-option -sa terminal-overrides ",xterm-ghostty.Tc"
set -g extended-keys on
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-yank'

run '~/.tmux/plugins/tpm/tpm'


#prev/next between windows
bind -n M-j previous-window
bind -n M-\; next-window

#Ctrl movenents between panels
bind -n C-j select-pane -L
bind -n C-k select-pane -D
bind -n C-l select-pane -U
bind -n C-\; select-pane -R

#source tmux.conf
bind r source-file ~/.tmux.conf \; display "reloaded"

#window/pane numbering
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set-option -g renumber-windows on

#Open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# tmux, vi copy mode 
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"

setw -g mode-keys vi

unbind-key -T copy-mode-vi h
unbind-key -T copy-mode-vi j
unbind-key -T copy-mode-vi k
unbind-key -T copy-mode-vi l

bind-key -T copy-mode-vi j send-keys -X cursor-left
bind-key -T copy-mode-vi k send-keys -X cursor-down
bind-key -T copy-mode-vi l send-keys -X cursor-up
bind-key -T copy-mode-vi \; send-keys -X cursor-right

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi V send-keys -X select-line

set -g set-clipboard off

